# Generated by Django 4.2.5 on 2023-09-26 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='%Y/%m/%d')),
                ('filename', models.CharField(max_length=255)),
                ('srs_wkt', models.CharField(max_length=255)),
                ('geom_type', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'uploadedFiles',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='building',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fileupload'),
        ),
        migrations.AddField(
            model_name='department',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fileupload'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fileupload'),
        ),
        migrations.AddField(
            model_name='province',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fileupload'),
        ),
        migrations.AddField(
            model_name='quarter',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fileupload'),
        ),
        migrations.AddField(
            model_name='risk',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fileupload'),
        ),
        migrations.AddField(
            model_name='riskarea',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fileupload'),
        ),
    ]
