# Generated by Django 4.2.5 on 2023-09-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fileupload_building_file_department_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='code_province',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
