# Generated by Django 4.2.5 on 2023-10-09 09:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_historicaldata_geo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_station', models.CharField(max_length=100)),
                ('geo', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.municipality')),
                ('quarter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.quarter')),
            ],
            options={
                'db_table': 'stations_service',
                'managed': True,
            },
        ),
    ]
