# Generated by Django 4.2.5 on 2023-10-10 09:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_gasstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=100, null=True)),
                ('road_distance', models.FloatField(default=0.0)),
                ('geo', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'roads',
                'managed': True,
            },
        ),
    ]
