# Generated by Django 4.2.5 on 2023-11-02 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_naturalenvironment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskarea',
            name='file',
        ),
    ]
