# Generated by Django 4.2.5 on 2023-11-05 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_riskarea_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskarea',
            name='typeRisk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typerisk'),
        ),
    ]
