# Generated by Django 4.2.5 on 2023-11-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_riskarea_typerisk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskarea',
            old_name='typeRisk',
            new_name='type_risk',
        ),
    ]
