# Generated by Django 4.2.5 on 2023-11-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_typerisk_riskarea_type_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskarea',
            name='file',
            field=models.FileField(null=True, upload_to='pictures/%Y/%m/%d'),
        ),
    ]
