# Generated by Django 4.2.5 on 2023-11-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_riskarea_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskarea',
            name='image_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
