# Generated by Django 4.2.5 on 2023-11-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_riskarea_image_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskarea',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='riskarea',
            name='user',
        ),
    ]
